version: '2.1'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ".:/app"
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    command: "bash entrypoint.sh"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - './front:/app'
